#!/usr/bin/env node
// Regenerates .claude/skills/abe-astro-library/references/component-index.md
// from every spec file under src/{components,sections,layouts}/<Name>/<Name>.md.
//
// Run via: npm run claude:reindex

import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(__dirname, '../../../..');
const SRC = join(PROJECT_ROOT, 'src');
const OUTPUT = join(
  PROJECT_ROOT,
  '.claude/skills/abe-astro-library/references/component-index.md',
);

/**
 * Tiny YAML frontmatter parser.
 *
 * Handles:
 *   - single-line `key: value`
 *   - block scalars: `key: |` (literal, lines joined with \n)
 *                    `key: >` (folded, lines joined with single space)
 *   - quoted strings (single or double)
 */
function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};
  /** @type {Record<string, string>} */
  const fm = {};
  const lines = match[1].split(/\r?\n/);
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    const colonIndex = line.indexOf(':');
    if (colonIndex < 1) {
      i++;
      continue;
    }
    const key = line.slice(0, colonIndex).trim();
    let value = line.slice(colonIndex + 1).trim();

    if (value === '|' || value === '>') {
      // Block scalar — collect indented continuation lines.
      const indicator = value;
      const parts = [];
      i++;
      let baseIndent = null;
      while (i < lines.length) {
        const next = lines[i];
        const indentMatch = next.match(/^( +)/);
        if (!indentMatch) break; // blank or unindented line ends block
        if (baseIndent === null) baseIndent = indentMatch[1].length;
        if (indentMatch[1].length < baseIndent) break;
        parts.push(next.trim());
        i++;
      }
      value = parts.join(indicator === '|' ? '\n' : ' ');
    } else {
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }
      i++;
    }
    fm[key] = value;
  }
  return fm;
}

/**
 * PascalCase → kebab-case. Handles acronym boundaries:
 *   FAQSection → faq-section
 *   AnswerCapsule → answer-capsule
 */
function pascalToKebab(s) {
  return s
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase();
}

/** Collapse newlines and runs of whitespace so the value fits in one table cell. */
function flatten(s) {
  return s.replace(/\s+/g, ' ').trim();
}

/**
 * Scan a group folder (components / sections / layouts) for `<Name>/<Name>.md`
 * spec files.
 */
function scanGroup(group) {
  const groupDir = join(SRC, group);
  let folders;
  try {
    folders = readdirSync(groupDir);
  } catch {
    return [];
  }

  const items = [];
  for (const folder of folders) {
    const folderPath = join(groupDir, folder);
    let stat;
    try {
      stat = statSync(folderPath);
    } catch {
      continue;
    }
    if (!stat.isDirectory()) continue;

    const specPath = join(folderPath, `${folder}.md`);
    let specContent;
    try {
      specContent = readFileSync(specPath, 'utf8');
    } catch {
      continue;
    }

    const fm = parseFrontmatter(specContent);
    const description = fm.description || fm.summary;

    items.push({
      name: folder,
      slug: pascalToKebab(folder),
      description: description
        ? flatten(description)
        : '_(no description in spec frontmatter)_',
    });
  }
  return items.sort((a, b) => a.name.localeCompare(b.name));
}

function renderSection(label, items) {
  if (items.length === 0) {
    return `## ${label}\n\n_No ${label.toLowerCase()} yet._\n`;
  }
  const rows = items
    .map((i) => `| \`${i.name}\` | \`${i.slug}\` | ${i.description} |`)
    .join('\n');
  return [
    `## ${label} (${items.length})`,
    '',
    '| Name | Slug | Description |',
    '|---|---|---|',
    rows,
  ].join('\n');
}

function buildIndex() {
  const groups = {
    layouts: scanGroup('layouts'),
    sections: scanGroup('sections'),
    components: scanGroup('components'),
  };

  const total =
    groups.layouts.length + groups.sections.length + groups.components.length;

  const header = [
    '# Component Index',
    '',
    '> Auto-generated by `scripts/generate-index.mjs`.',
    '> Do not edit by hand. Run `npm run claude:reindex` to refresh.',
    '>',
    `> Last generated: ${new Date().toISOString().slice(0, 10)} — ${total} items.`,
    '',
  ].join('\n');

  return [
    header,
    renderSection('Layouts', groups.layouts),
    '',
    renderSection('Sections', groups.sections),
    '',
    renderSection('Components', groups.components),
    '',
    '---',
    '',
    '## How to add a component',
    '',
    'Create a folder under `src/components/`, `src/sections/`, or `src/layouts/` with the three-file shape:',
    '',
    '```',
    'src/components/Foo/',
    '├── Foo.astro            # the component',
    '├── Foo.md               # the spec',
    '└── Foo.examples.astro   # variants for the styleguide',
    '```',
    '',
    'Then run `npm run claude:reindex`.',
    '',
  ].join('\n');
}

const output = buildIndex();
writeFileSync(OUTPUT, output, 'utf8');
console.log(`✓ Wrote ${OUTPUT}`);
